### {{ name }} Configuration Settings
---

{{ label }}:
  # my_option: 101


log.logging:

### Where the log file lives (no log file by default)
# file: null

### The level for which to log.  One of: info, warning, error, fatal, debug
# level: info

### Whether or not to log to console
# to_console: true

### Whether or not to rotate the log file when it reaches `max_bytes`
# rotate: false

### Max size in bytes that a log file can grow until it is rotated.
# max_bytes: 512000

### The maximum number of log files to maintain when rotating
# max_files: 4
